# Generated by Django 6.0.6 on 2026-07-12 19:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('e27bae48-0694-488e-ac39-d3d8dca8b1f4'), editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('classe', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('d76baeb7-f740-421a-9535-618a69062ffa'), editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_livraision', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Plat',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('02a0299c-329c-4ceb-b2b0-2ef4baffb58a'), editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('details', models.TextField(null=True)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='plats/')),
                ('price', models.FloatField()),
                ('disponibility', models.BooleanField(default=True)),
            ],
        ),
    ]
