# Generated by Django 6.0.6 on 2026-07-13 13:38

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restfull', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plat',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c26f3ebc-707f-4a10-a891-f03f2ed41db6'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='id',
            field=models.UUIDField(default=uuid.UUID('85113632-f755-452a-9500-5aab39dd47b0'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='plat',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3057e174-7cd0-4fef-b7a1-e7a70933abdd'), editable=False, primary_key=True, serialize=False),
        ),
    ]
