# Generated by Django 6.0.6 on 2026-07-16 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restfull', '0003_alter_client_id_alter_commande_id_alter_plat_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='date_livraision',
            new_name='date_livraison',
        ),
        migrations.AddField(
            model_name='commande',
            name='status',
            field=models.CharField(choices=[('LIVREE', 'Livrée'), ('ANNULEE', 'Annulée'), ('EN_ATTENTE', 'En attente'), ('EN_PREPARATION', 'En préparation'), ('PRETE', 'Prête'), ('CONFIRMER', 'Confirmer')], default='EN_ATTENTE', max_length=20),
        ),
    ]
